platform :ios, "7.0"

pod 'FIR.im', '~> 1.2.0'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'Mantle'
pod 'Masonry'
pod 'Reachability'
pod 'BlocksKit'
pod 'KVOController'
pod 'MBProgressHUD'
pod 'ODRefreshControl'
pod 'pop'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'TTTAttributedLabel'
pod 'UITableView+FDTemplateLayoutCell'
pod 'SVPullToRefresh'
pod 'UMengAnalytics'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengFeedback'